### ISSUE TITLE
Why are you using both str and bytes?

### ISSUE THREAD

**Issue by elisbyberi** [InSyncWithFoo/character-range#2]
You should work with `str` only; decode and encode the user's bytes input.

This is the root of all the problems: `_StrOrBytes = TypeVar('_StrOrBytes', str, bytes)`

https://github.com/InSyncWithFoo/character-range/blob/4190026af988a5ac17e16ed0fe80e8ed5219ca8f/src/character_range/string_and_bytes_range.py#L19C6-L19C6

**Comment by InSyncWithFoo** [comment]
From [the post on discuss.python.org](https://discuss.python.org/t/get-single-byte-bytes-objects-from-a-bytes-object/41709/10):

> Since `bytes` and `str` have enough similarities for even some libraries in the stdlib to support both more or less the same (e.g. [`os.PathLike`](https://docs.python.org/3/library/os.html#os.PathLike) or [`re.Pattern`](https://docs.python.org/3/library/re.html#re.Pattern)), I think support for bytes ranges would be a nice feature to have.

That was a deliberate design choice, so I don't feel like rewriting the whole codebase, sorry.
